### ISSUE TITLE
PUT-Methode antwortet mit 400 Bad Request #RIP_Repo3

### ISSUE THREAD

**Issue by GurkenKater** [int-lecture/repo-03#1]
curl -v -H "Content-Type: application/json" -X PUT -d '{"to":"Luca","from":"T.Smits","date":"2017-04-26T11:30:30Z","text":"Mambolea, mamboleo"}' 141.19.142.57:5000/send

Bekomme Bad Request Antwort

In your Mouth!

**Comment by MorMundHS-MA** [comment]
Reviewed : "2017-04-26T11:30:30Z" -> "2017-04-26T11:30:30+0200"
