### ISSUE TITLE
Frontend Gruppe 3 <-> Backend Gruppe 1

### ISSUE THREAD

**Issue by ChristopherRotter** [int-lecture/repo-03#8]
Nach dem Login wird man nach einer Sekunde wieder rausgeworfen (code 401).

**Comment by MorMundHS-MA** [comment]
Wir senden in unserem Authorization header das Token in der Form " Token [das Token]" wie in   
[Assignment 6](https://github.com/int-lecture/assignments/tree/master/assignment06#empfangen-von-nachrichten) beschrieben. Eventuell erwartet euer Backend das Token in einer anderen Form.
